import type React from "react"

export const metadata = {
  he: {
    title: "סטודיו סשה Tattoos — אומנות קעקועים",
    description: "סטודיו ביחס אישי ועבודה מדויקת",
  },
  en: {
    title: "Studio Sasha Tattoos — Tattoo Art",
    description: "Personal attention studio with precise work",
  },
  es: {
    title: "Studio Sasha Tattoos — Arte de Tatuajes",
    description: "Estudio con atención personal y trabajo preciso",
  },
  ru: {
    title: "Studio Sasha Tattoos — Искусство татуировок",
    description: "Студия с личным подходом и точной работой",
  },
  ar: {
    title: "Studio Sasha Tattoos — فن الوشم",
    description: "استوديو برعاية شخصية وعمل دقيق",
  },
  th: {
    title: "Studio Sasha Tattoos — ศิลปะรอยสักสวยงาม",
    description: "สตูดิโอที่ให้ความสนใจส่วนบุคคลและการทำงานที่แม่นยำ",
  },
}

export const languages = {
  he: { name: "עברית", flag: "🇮🇱", dir: "rtl" },
  en: { name: "English", flag: "🇺🇸", dir: "ltr" },
  es: { name: "Español", flag: "🇪🇸", dir: "ltr" },
  ru: { name: "Русский", flag: "🇷🇺", dir: "ltr" },
  ar: { name: "العربية", flag: "🇸🇦", dir: "rtl" },
  th: { name: "ไทย", flag: "🇹🇭", dir: "ltr" },
}

export const translations = {
  he: {
    title: "סטודיו סשה Tattoos",
    subtitle: "סטודיו ביחס אישי ועבודה מדויקת",
    location: "טבריה 📍",
    phone: "052-620-2701",
    rateUs: "⭐ דרגו אותנו!",
    shareWithFriend: "💖 ספרו לחבר",
    portfolio: "תיקיית עבודות 📸",
    address: "עליזה בגין 123 טבריה",
    allRightsReserved: "כל הזכויות שמורות לשוהם תייטלר",
    copyright: "© {year} סטודיו סשה Tattoos",
    linkCopied: "הקישור הועתק 🙂",
    copyFailed: "לא הצלחתי להעתיק, אפשר להעתיק ידנית.",
    shareNotSupported: "הדפדפן לא תומך בשיתוף. העתק/י את הכתובת מהשורת כתובת.",
    ratingComplete: "תודה רבה, דעתך חשובה לנו",
    ratingError: "אירעה שגיאה בשליחת הדעה",
  },
  en: {
    title: "Studio Sasha Tattoos",
    subtitle: "Personal attention studio with precise work",
    location: "Tiberias 📍",
    phone: "052-620-2701",
    rateUs: "⭐ Rate Us!",
    shareWithFriend: "💖 Share With Friend",
    portfolio: "Portfolio 📸",
    address: "Eliza Begin 123 Tiberias",
    allRightsReserved: "All rights reserved Shoam Taitler",
    copyright: "© {year} Studio Sasha Tattoos",
    linkCopied: "Link copied 🙂",
    copyFailed: "Couldn't copy, you can copy manually.",
    shareNotSupported: "Browser does not support sharing. Copy the address from the address bar.",
    ratingComplete: "Thank you, your opinion matters to us",
    ratingError: "Error submitting feedback",
  },
  es: {
    title: "Studio Sasha Tattoos",
    subtitle: "Estudio con atención personal y trabajo preciso",
    location: "Tiberíades 📍",
    phone: "052-620-2701",
    rateUs: "⭐ Calificanos!",
    shareWithFriend: "💖 Comparte con un Amigo",
    portfolio: "Portafolio 📸",
    address: "Eliza Begin 123 Tiberíades",
    allRightsReserved: "Todos los derechos reservados Shoam Taitler",
    copyright: "© {year} Studio Sasha Tattoos",
    linkCopied: "Enlace copiado 🙂",
    copyFailed: "No se pudo copiar, copia manualmente.",
    shareNotSupported: "El navegador no es compatible con compartir. Copia la dirección de la barra de direcciones.",
    ratingComplete: "Gracias, tu opinión nos importa",
    ratingError: "Error al enviar comentarios",
  },
  ru: {
    title: "Studio Sasha Tattoos",
    subtitle: "Студия с личным подходом и точной работой",
    location: "Тверия 📍",
    phone: "052-620-2701",
    rateUs: "⭐ Оцените Нас!",
    shareWithFriend: "💖 Поделитесь с Другом",
    portfolio: "Портфолио 📸",
    address: "Элиза Бигин 123 Тверия",
    allRightsReserved: "Все права защищены Шоам Тейтлер",
    copyright: "© {year} Studio Sasha Tattoos",
    linkCopied: "Ссылка скопирована 🙂",
    copyFailed: "Не удалось скопировать, скопируйте вручную.",
    shareNotSupported: "Браузер не поддерживает общий доступ. Скопируйте адрес из адресной строки.",
    ratingComplete: "Спасибо, ваше мнение важно для нас",
    ratingError: "Ошибка при отправке отзыва",
  },
  ar: {
    title: "Studio Sasha Tattoos",
    subtitle: "استوديو برعاية شخصية وعمل دقيق",
    location: "طبريا 📍",
    phone: "052-620-2701",
    rateUs: "⭐ قيمونا!",
    shareWithFriend: "💖 شارك مع صديق",
    portfolio: "المحفظة 📸",
    address: "اليزا بيجين 123 طبريا",
    allRightsReserved: "جميع الحقوق محفوظة شوام تايتلر",
    copyright: "© {year} Studio Sasha Tattoos",
    linkCopied: "تم نسخ الرابط 🙂",
    copyFailed: "لم يتمكن من النسخ، يرجى النسخ يدويا.",
    shareNotSupported: "المتصفح لا يدعم المشاركة. انسخ العنوان من شريط العنوان.",
    ratingComplete: "شكراً لك، رأيك مهم لنا",
    ratingError: "خطأ في إرسال التعليق",
  },
  th: {
    title: "Studio Sasha Tattoos",
    subtitle: "สตูดิโอที่ให้ความสนใจส่วนบุคคลและการทำงานที่แม่นยำ",
    location: "ทิเบเรียส 📍",
    phone: "052-620-2701",
    rateUs: "⭐ ให้คะแนนเรา!",
    shareWithFriend: "💖 แชร์กับเพื่อน",
    portfolio: "แกลเลอรี่ 📸",
    address: "อีลิซา บีจิน 123 ทิเบเรียส",
    allRightsReserved: "สงวนลิขสิทธิ์ Shoam Taitler",
    copyright: "© {year} Studio Sasha Tattoos",
    linkCopied: "คัดลอกลิงก์แล้ว 🙂",
    copyFailed: "ไม่สามารถคัดลอกได้ โปรดคัดลอกด้วยตนเอง",
    shareNotSupported: "เบราว์เซอร์ไม่รองรับการแชร์ คัดลอกที่อยู่จากแถบที่อยู่",
    ratingComplete: "ขอบคุณ ความคิดเห็นของคุณสำคัญกับเรา",
    ratingError: "เกิดข้อผิดพลาดในการส่งข้อมูล",
  },
}
